name: Generate Packs Metadata

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'metadata/**'
      - 'README.md'
      - '.gitignore'

jobs:
  generate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml packaging

      - name: Generate metadata JSON
        run: python generate_packs_metadata.py

      - name: Commit and push metadata
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add metadata/packs_metadat.json
          git commit -m "Auto-update packs_metadat.json" || echo "No changes to commit"
          git push

