name: Generate Metadata

on:
  push:
    branches: [main]

jobs:
  generate:
    name: Generate Metadata
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install pyyaml packaging
      - name: Run metadata generation
        run: python scripts/generate_packs_metadata.py
      - name: Commit and push metadata
        run: |
          if git diff --quiet --exit-code metadata/; then
            echo "✅ No metadata changes to commit."
          else
            echo "📦 Committing updated metadata..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add metadata/packs_metadata.json
            git add metadata/latest_packs_meta.json
            git add metadata/latest_packs.md
            git commit -m "Auto-update packs metadata"
            git push
          fi

