name: Validate Pack Structure

on:
  push:
    branches: ["**"]

jobs:
  validate:
    name: Validate Structure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install pyyaml
      - name: Run validation
        run: python scripts/validate_pack_structure.py

